#ifndef COMPONENT_TYPES
#define COMPONENT_TYPES

typedef void *Component;

typedef enum {
  UCT_POSITION,
  UCT_SIZE,
  UCT_MOVEMENT,
  UCT_PLAYERCONTROLLABLE,
  UCT_TOTAL_UCOMPONENT_TYPES
} UComponentType;

typedef enum {
  DCT_SHADOW,
  DCT_RECTANGLE_SHAPE,
  DCT_TOTAL_DCOMPONENT_TYPES
} DComponentType;

#endif // COMPONENT_TYPES
